# Generated by Django 5.2.7 on 2025-10-24 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('production_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_serial_number', models.CharField(max_length=100, unique=True)),
                ('assembly_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('assembled', 'Assembled'), ('functional_tested', 'Functional Tested'), ('environmental_tested', 'Environmental Tested'), ('final_functioned_tested', 'Final Functional Tested'), ('completed', 'Completed')], default='assembled', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('assembler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembled_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assembly_date'],
            },
        ),
        migrations.CreateModel(
            name='ModuleTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('functional', 'Functional Test'), ('environmental', 'Environmental Test'), ('final_functional', 'Final Functional Test')], max_length=20)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_records', to='pcb_tracker.module')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Testing'), ('tested', 'Tested by Board Tester'), ('qa_verified', 'Verified by QA'), ('assembled', 'Assembled into Module'), ('functional_tested', 'Functional Tested'), ('environmental_tested', 'Environmental Tested'), ('final_functional_tested', 'Final Functional Tested'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcbs', to='pcb_tracker.batch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='pcbs',
            field=models.ManyToManyField(related_name='modules', to='pcb_tracker.pcb'),
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pcb_test', 'PCB Test Report'), ('functional_test', 'Functional Test Report'), ('environmental_test', 'Environmental Test Report'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='attachments/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pcb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pcb_tracker.pcb')),
            ],
        ),
        migrations.CreateModel(
            name='TestMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('current', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('other_measurements', models.JSONField(blank=True, default=dict)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('pcb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='pcb_tracker.pcb')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('level', models.IntegerField(help_text='Level of the group (e.g., 1 for lvl1, 2 for lvl2)')),
                ('department', models.CharField(help_text='Department the group belongs to', max_length=50)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
