# Generated by Django 5.2.7 on 2025-10-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_tracker', '0002_create_user_groups'),
        ('pcb_tracker', '0003_create_production_summary_group'),
    ]

    operations = [
    ]
