# Generated by Django 5.2.7 on 2025-10-25 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_tracker', '0007_create_manage_pcb_type_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pcb_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_configs', to='pcb_tracker.pcbtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pcb',
            name='test_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcbs', to='pcb_tracker.testconfig'),
        ),
        migrations.AddField(
            model_name='testmeasurement',
            name='test_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_measurements', to='pcb_tracker.testconfig'),
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.CharField(choices=[('voltage', 'Voltage'), ('current', 'Current'), ('frequency', 'Frequency'), ('resistance', 'Resistance'), ('temperature', 'Temperature'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('unit', models.CharField(default='V', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('test_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='pcb_tracker.testconfig')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('test_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pcb_tracker.testconfig')),
            ],
            options={
                'ordering': ['order', 'question_text'],
            },
        ),
        migrations.CreateModel(
            name='ParameterMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('test_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_measurements', to='pcb_tracker.testmeasurement')),
                ('test_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcb_tracker.testparameter')),
            ],
            options={
                'unique_together': {('test_measurement', 'test_parameter')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('test_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='pcb_tracker.testmeasurement')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcb_tracker.testquestion')),
            ],
            options={
                'unique_together': {('test_measurement', 'test_question')},
            },
        ),
    ]
